#ifndef ROBOTDEFINES_H
#define ROBOTDEFINES_H

// PWM channels for each motor in the drive train

#define PWM_FRONT_LEFT_MOTOR 4
#define PWM_BACK_LEFT_MOTOR 2
#define PWM_FRONT_RIGHT_MOTOR 3
#define PWM_BACK_RIGHT_MOTOR 1

#define SOLENOID_CATAPULT_HIGH 1
#define SOLENOID_CATAPULT_LOW 2

#define SOLENOID_KICKER_HIGH 3
#define SOLENOID_KICKER_LOW 4

#define SOLENOID_INTAKE_LEFT_HIGH 5
#define SOLENOID_INTAKE_LEFT_LOW 6

#define SOLENOID_INTAKE_RIGHT_LOW 7
#define SOLENOID_INTAKE_RIGHT_HIGH 8

#define GYRO_CHANNEL 1

#define COMPRESSOR_SWITCH_CHANNEL 2
#define COMPRESSOR_RELAY_CHANNEL 1

#endif
